### PR TITLE
0.20180819

### PR DESCRIPTION
**Pull request by zvezdochiot**
realloc buffer stdin

### CODE REVIEW

**Comment by jgilje** [comment]
Thanks, are you able to create a PR without all the v2m-files checked in?

**Comment by zvezdochiot** [comment]
Ok. Modify. Only 0test.v2m and Dafunk--breeze.v2mz (samples README.md)

**Comment by jgilje** [comment]
Thanks

**Comment by jgilje** [comment]
Oh, I meant to remove the v2m files in the v2m subfolder. Nevermind, it's merged now :)

**Comment by zvezdochiot** [comment]
Hmm.
What for?
I catch errors with this collection.

**Comment by jgilje** [comment]
Sorry, My bad! I just assumed it was a random collection of tunes, I didn't consider that they're for testing.

**Comment by zvezdochiot** [comment]
[0.20180108 - Fix time play] caught with her help
[0.20180818 - fix stdin buffer size] caught with her help
Without it, nothing would have happened.

**Pull request merged**
